Implement option to start at a specific exercise in debug mode
danwritecode/clings pull request #160
Opened 2024-06-11 11:54 UTC by louis77

A humble first try to tackle issue #156 :-)

2024-06-11 13:28 UTC, danwritecode commented
Thinking about this one more, I think we probably should support this feature in both normal and debug modes. Debug mode doesn't allow you to fully test (at least right now) and if someone is developing a new exercise they need to be able to actually run it. 

Do you mind updating? Sorry about that, didn't think of it when I was creating the issue.

2024-06-11 14:21 UTC, louis77 commented
Agree. I've removed the 2nd commit, so now it's available in non-debug mode, too. That's probably also more useful if more CLI flags are added in the future.

2024-06-11 23:18 UTC, danwritecode requested changes
Looks good, just want to add a check for optarg.

2024-06-11 23:18 UTC, danwritecode commented on src/main.c
> +                start_at = atoi(optarg);
Could you add a check here to make sure optarg isn't null? if it is null, then we should display some message that the -s requires a number to start at

2024-06-11 23:52 UTC, danwritecode requested changes

2024-06-11 23:52 UTC, danwritecode commented on src/main.c
> +    while ((c = getopt(argc, argv, "s::")) != -1) {
should this be "s:" this way the argument can be passed with a space?

2024-06-13 23:03 UTC, danwritecode approved these changes

2024-06-13 23:03 UTC, merged