Setup script
danwritecode/clings pull request #182
Opened 2024-07-26 16:24 UTC by tunahorse

Made a small bash script to get going right away. Windows presents some issues, for linux only now.

2024-08-01 03:35 UTC, danwritecode commented on start.sh
> +apt-get install -y build-essential
Could you remove -y? Reason in next comment.

2024-08-01 03:39 UTC, danwritecode requested changes
Left a few comments, also, we should probably call this "start_debian.sh"

I use ubuntu so I won't be able to test any other distros, but at least we can start by supporting debian based distros.

2024-08-01 03:39 UTC, danwritecode commented on start.sh
> +apt-get install -y build-essential
I think we should probably remove all "-y" and explicitly tell the user "You don't have xyz installed, do you want to install it now?"...claude suggests something like this to check if someone has build-essentials installed: 

```bash
if ! dpkg -s build-essential &> /dev/null; then
    echo "build-essential is not installed. Please install it using: sudo apt-get install build-essential"
    exit 1
fi
```

2024-08-01 03:39 UTC, danwritecode commented on start.sh
> +    apt-get install -y tmux
Same thing here but you can just do `which tmux` to see if it's installed

2024-08-01 03:39 UTC, danwritecode commented on start.sh
> +    git clone https://github.com/danwritecode/clings.git
should probably check if they have Git installed also with `which git`

2024-08-06 21:35 UTC, tunahorse commented
Updated !

2024-08-07 22:31 UTC, danwritecode approved these changes

2024-08-07 22:32 UTC, danwritecode commented
this is awesome!!! merging now

2024-08-07 22:32 UTC, merged